<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Options" Version="8.0.0" />
    <PackageVersion Include="MailKit" Version="4.11.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.3" />
    <PackageVersion Include="MimeKit" Version="4.11.0" />
    <PackageVersion Include="Dapper" Version="2.1.66" />
    <PackageVersion Include="Npgsql" Version="9.0.3" />
    <PackageVersion Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>
</Project>